import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createInitialCharacter } from "../src/lib/character";
import { normalizeItemContent, purchaseItem, setItemEmEncaixe, equipDefensiveItem, setItemLoadoutState } from "../src/lib/character/inventory";
import { projectBodySlots } from "../src/app/ficha/_console/slots";
import { espacosDaInstancia, resumoDeCarga } from "../src/lib/character/carga";
import { loadAmmoSupport, reloadFromInventory } from "../src/lib/character/ammunitionSupport";
import { checkAttackAmmoBlock, consumeAttackAmmo } from "../src/lib/character/ammunition";
import { weaponRangeAt } from "../src/lib/character/weaponRange";
import { normalizeItemProperty } from "../src/lib/character/inventory";
import { resolveAttackDetails } from "../src/lib/character/attackWeapon";
const folder="content/v12/revisao-2026-10-10-atualizada/";
const rows=JSON.parse(readFileSync(folder+"catalogo-candidato.json","utf8")).registros;
const diff=JSON.parse(readFileSync(folder+"diff-revisao.json","utf8"));
assert.deepEqual(diff.avisos, []);
assert.deepEqual(diff.ausentes_na_fonte_atual.map((r:any)=>r.slug).sort(),["armas_retornavel","armas_armas_de_fogo_serpentina","armas_armas_de_fogo_ricochete"].sort());
const items=rows.filter((r:any)=>r.content_type==="item").map((r:any)=>normalizeItemContent(r.payload));
const find=(name:string)=>{const item=items.find((i:any)=>i.nome===name);assert(item,name);return item;};
const weapons=items.filter((i:any)=>i.categoria==="arma");
assert.equal(weapons.length,78);assert.equal(weapons.filter((i:any)=>i.maos===1).length,28);assert.equal(weapons.filter((i:any)=>i.maos===2).length,50);
for(const name of ["Carabina","Escopeta curta"])assert.equal(find(name).raridade,"incomum");
assert.equal(find("Carabina").preco,1500);assert.equal(find("Escopeta curta").preco,1000);
for(const weapon of weapons.filter((i:any)=>i.subtipo!=="ARMAS BRANCAS"))assert(weapon.usesAmmunition,weapon.nome);
const wrecker=find("AS-127 Wrecker (Rifle antimaterial)");
assert.equal(wrecker.municaoMax,1);
assert.equal(wrecker.municaoCompativelSlug,"mun_precisao");
assert(find("Precisão").ammoArmasCompativeis.includes(wrecker.slug));
const catalog=new Map(items.map((i:any)=>[i.slug,i])) as Map<string,ReturnType<typeof normalizeItemContent>>;
let character={...createInitialCharacter(null,"Atualização Notion"),carteira:{aretz_informal:100000,cdi:0,cdi_craqueada:0}};
const buy=(name:string)=>{const result=purchaseItem({character,item:find(name),quantidade:1,walletId:"aretz_informal",nowIso:"2026-10-10T00:00:00Z",catalog:items});assert(result.ok);character=result.character as typeof character;return result.instance!;};
for(const [name,units,price] of [["Facas de Arremesso",4,120],["Shuriken",6,200],["RV-12 Razorstar (Shuriken)",3,1000]] as const){const before=character.carteira.aretz_informal;const instance=buy(name);assert.equal(instance.quantidade,units);assert.equal(before-character.carteira.aretz_informal,price);assert.equal(espacosDaInstancia(instance,find(name)),1);assert.equal(espacosDaInstancia({...instance,quantidade:1},find(name)),1);}
const one=buy("Faca"),two=buy("Manoplas"),shield=buy("Escudo compacto");
character=setItemEmEncaixe(character,two.id,"arma_primaria",catalog) as typeof character;
let projected=projectBodySlots(character.inventario??[],catalog);
assert.equal(projected.slots.find(s=>s.id==="arma_primaria")!.instance?.id,two.id);assert.equal(projected.slots.find(s=>s.id==="arma_secundaria")!.instance?.id,two.id);
character=equipDefensiveItem(character,shield.id,find("Escudo compacto"),catalog) as typeof character;
assert.equal(character.inventario?.find(i=>i.id===two.id)?.estado,"mochila");
character=setItemEmEncaixe(character,one.id,"arma_secundaria",catalog) as typeof character;
assert.equal(character.inventario?.find(i=>i.id===shield.id)?.equipadoDefensivo,false);
const support=buy("Aljava"), arrows=buy("Flecha simples"), bolts=buy("Virotes");
const profiles=items.filter((i:any)=>i.categoria==="municao").map((i:any)=>({slug:i.slug,nome:i.nome,familia:i.ammoFamilia,armasCompativeis:i.ammoArmasCompativeis,kitQuantidade:i.ammoKitQuantidade}));
const heavy=buy("AS-127 Wrecker (Rifle antimaterial)");const precision=buy("Precisão");
const heavyReload=reloadFromInventory(character,heavy.id,wrecker,profiles);
assert.equal(heavyReload.carregada,1);assert.equal(heavyReload.custoPa,2);
assert.equal(heavyReload.character.inventario?.find(i=>i.id===precision.id)?.quantidade,4);
const filled=loadAmmoSupport(character,support.id,profiles);character=filled.character as typeof character;
const stored=character.inventario?.find(i=>i.id===support.id)!.aljava!;
assert.equal(stored.stacks.reduce((n,s)=>n+s.quantidade*(s.pesoCapacidade??1),0),20);
assert.equal(stored.stacks.find(s=>s.contentSlug===bolts.itemSlug)?.quantidade,5);
assert.equal(stored.stacks.find(s=>s.contentSlug===arrows.itemSlug)?.quantidade,10);
character=setItemEmEncaixe(character,support.id,"suporte_municao",catalog) as typeof character;
const bow=buy("Arco curto");assert.equal(checkAttackAmmoBlock(character,items,{weaponInstanceId:bow.id}),"sem_municao");
const reload=reloadFromInventory(character,bow.id,find("Arco curto"),profiles);assert.equal(reload.custoPa,1);assert.equal(reload.carregada,1);character=reload.character as typeof character;
assert.equal(checkAttackAmmoBlock(character,items,{weaponInstanceId:bow.id}),null);
assert.equal(consumeAttackAmmo(character,items,{weaponInstanceId:bow.id}).character.inventario?.find(i=>i.id===bow.id)?.municaoAtual,0);
const gun=buy("Carabina");buy("Fuzil");const backpackReload=reloadFromInventory(character,gun.id,find("Carabina"),profiles);assert.equal(backpackReload.custoPa,2);assert.equal(backpackReload.carregada,20);
const energy=buy("Crioagulha"),cell=buy("Compacta");const swap=reloadFromInventory(character,energy.id,find("Crioagulha"),profiles);assert.equal(swap.carregada,8);assert(swap.character.inventario?.some(i=>i.itemSlug===cell.itemSlug&&i.cargasAtual===0),"Célula vazia preservada");
const knife=find("Facas de Arremesso");const action={} as Parameters<typeof resolveAttackDetails>[1];
assert.equal(resolveAttackDetails(character,action,knife,"arremesso").danoBase,"1d6");assert.equal(resolveAttackDetails(character,action,knife,"corpo_a_corpo").danoBase,"1d4");assert.equal(resolveAttackDetails(character,action,knife,"arremesso").skill,"precisao");
for(const name of ["Crioagulha","Criojetor","Lança-crio"])assert(find(name).propertySlugs.includes("congelamento"));
assert(find("Ofuscador").propertySlugs.includes("ofuscamento"));assert(find("Disruptor").propertySlugs.includes("disrupcao"));
console.log("✓ Notion atual: 78 armas, mãos exclusivas, kits, dois ataques, suportes mistos, recarga e células preservadas");

assert.equal(weaponRangeAt(find("Carabina"), find("Carabina").alcance!.eficazM!).penalty,0);
assert.equal(weaponRangeAt(find("Carabina"), find("Carabina").alcance!.eficazM!+1).penalty,-2);
assert.equal(weaponRangeAt(find("Carabina"), find("Carabina").alcance!.maxM!+1).allowed,false);
assert.equal(weaponRangeAt(knife,2,"corpo_a_corpo").allowed,false);
const props=JSON.parse(readFileSync(folder+"propriedades-atualizadas.json","utf8"));
for(const r of props) assert(normalizeItemProperty({id:r.slug,slug:r.slug,nome:r.payload.nome,raw:r.payload,status:"published",descricaoCurta:r.payload.descricao_curta,payloadAutomacao:r.payload.payload_automacao} as any).critical);
console.log("✓ Alcance eficaz, penalidade, alcance máximo e novas propriedades críticas");

const storage=character.inventario!.find(i=>i.id===support.id)!;
assert.equal(resumoDeCarga({...character,inventario:[{...storage,estado:"mochila",aljava:{capacidade:20,tipo:"aljava",stacks:[{contentSlug:arrows.itemSlug,nome:"Flechas",quantidade:10},{contentSlug:bolts.itemSlug,nome:"Virotes",quantidade:5,pesoCapacidade:2}]}}]},catalog).ocupados,3);
assert.equal(resumoDeCarga({...character,inventario:[{...storage,estado:"equipado"}]},catalog).ocupados,0);
console.log("✓ Suporte guardado conta sua munição; suporte equipado não ocupa mochila");

const flightA=buy("Icarus I"),flightB=buy("Icarus II"),gloves=buy("Luvas de Escalada");
character=setItemLoadoutState(character,flightA.id,"equipado",catalog) as typeof character;
character=setItemLoadoutState(character,gloves.id,"equipado",catalog) as typeof character;
character=setItemLoadoutState(character,flightB.id,"equipado",catalog) as typeof character;
assert.equal(character.inventario?.find(i=>i.id===flightA.id)?.estado,"mochila");
assert.equal(character.inventario?.find(i=>i.id===gloves.id)?.estado,"equipado");
console.log("✓ Estrutura dorsal exclusiva, independente da posição de Luvas");
