/** Ficha mínima de personagem do Ruptura VTT — ponto de entrada único. */

export * from "./types";
export * from "./derived";
export * from "./createCharacter";
export * from "./normalizeCharacter";
export * from "./activeEffects";
export * from "./autoHeal";
export * from "./rest";
export * from "./overload";
export * from "./collapse";
export * from "./evolution";
export * from "./actionConsole";
export * from "./reactions";
export * from "./endRoundConditions";
export * from "./rupture";
export * from "./attack";
export * from "./talents";
export * from "./talentEngine";
export * from "./inventory";
export * from "./spells";
export * from "./escalpos";
export * from "./technicalEffects";
export * from "./defense";
export * from "./ammunition";
export * from "./gmActions";
export * from "./attackWeapon";
export * from "./itemUse";
export * from "./temporaryEffects";
